- build_deploy.sh
- pr_check.sh
Adding Integration Pipeline
Under: https://issues.redhat.com/browse/CSSRE-1923
> adding Integration Pipeline

- build_deploy.sh
> deploy script modification

- build_deploy.sh
- sre/Dockerfile.sre
> adding integration job files

- sre/Dockerfile.sre
Moving away from Docker Images
> updating base image

- build_deploy.sh
adding git commit hash to be used as Image tag
> adding git commit hash

- k8s-manifests/beat-deployment.yaml
- k8s-manifests/glitchtip.yaml
> correcting manifest files

- k8s-manifests/beat-deployment.yaml
- k8s-manifests/glitchtip-configmap.yaml
- k8s-manifests/migrate-job.yaml
- k8s-manifests/web-deployment.yaml
- k8s-manifests/web-service.yaml
- k8s-manifests/worker-deployment.yaml
> updating deploy files

- openshift/template.yaml
> Adding Openshift template

- openshift/template.yaml
> updating template parameters

- openshift/template.yaml
> glitchtip deployment fixes

- openshift/template.yaml
> fixing template

- openshift/template.yaml
> Fixing Beat deployment files

- openshift/template.yaml
Beat is getting config error in deployments
> fixing beat deployments

- openshift/template.yaml
> adding redis details

- openshift/template.yaml
Re Adding Auth Token for Debug Purposes
> re-adding Redis Password

- sre/Dockerfile.sre
The application is not able to recognize the Template folder in Django. 
This is a attempt to fix the error
> fixing build image

- openshift/template.yaml
Adding a new Temporary Secret to reference`redis creds`
> fixing redis connection

- openshift/template.yaml
adding redis URL
Fixing Worker REDIS_URL
> adding redis URL

- openshift/template.yaml
Creating a Job for a SuperUser
> adding superuser job

- openshift/template.yaml
> Fixing SuperUser Job

- openshift/template.yaml
Job unable to update due to immutable types
> fixing immutable types

- openshift/template.yaml
> adding password hash token

- openshift/grafana-dashboard-glitchtip.configmap.yaml
> adding grafana dashboard

- .github/workflows/pr_checks.yml
Hi @deepak1725 , just changed the github action to validate all files in openshift folder, please give this a look
> oc lint check for files in openshift/ folder

- openshift/template.yaml
Adding Liveness and Readiness Probes
[CSSRE-2003](https://issues.redhat.com/browse/CSSRE-2003)
[CSSRE-2004](https://issues.redhat.com/browse/CSSRE-2004)
> adding liveness and readiness probes

- openshift/template.yaml
[CSSRE-2002](https://issues.redhat.com/browse/CSSRE-2002)
[CSSRE-2005](https://issues.redhat.com/browse/CSSRE-2005)
> adding limits to Superuser Job

- openshift/template.yaml
Updating Name of SuperUser Job coz Jobs fields are Immutable
> updating name of superuser job

- openshift/template.yaml
[CSSRE-2004](https://issues.redhat.com/browse/CSSRE-2004)
> adding probes in gt-beat and GT Worker

- openshift/template.yaml
GT Worker is not exposing any Endpoint. Falling Back to another method of Probing
> fixing worker probes

- openshift/template.yaml
Adding Probe delay time to allow celery to bootup
> Adding probing delay time

- sre/Dockerfile.sre
Fixing Permission Error
Ref : [here](https://coreos.slack.com/archives/C02CMTM9GG1/p1653312107076389)
> fixing permission errors

- sre/Dockerfile.sre
> fixing permissions of celerybeat scheduler

- sre/Dockerfile.sre
Reverts rh-cssre/glitchtip-frontend#69
> Revert "fixing permissions of celerybeat scheduler"

- openshift/template.yaml
- sre/Dockerfile.sre
**Reverting Fixes done in:**
- https://github.com/rh-cssre/glitchtip-frontend/pull/73 
- https://github.com/rh-cssre/glitchtip-frontend/pull/72
- https://github.com/rh-cssre/glitchtip-frontend/pull/71
- https://github.com/rh-cssre/glitchtip-frontend/pull/68
> reverting temp fixes

- openshift/kubernetes/README.md
- openshift/kubernetes/k8s.yaml
Adding Manifest File and Documentation for Local Installation of Glitchtip
> adding glitch-tip local installation

- openshift/template.yaml
Fixing Job to remove all completed jobs
> Fixing Job template to remove completed jobs

- openshift/grafana/grafana-dashboard-glitchtip.configmap.yaml
added the modified grafana dashboard based on proposed SLOs
modified the glitchtip grafana dashboard based on the proposed SLOs
https://issues.redhat.com/browse/CSSRE-2052
> modified the gt-grafana dashboard

- openshift/template.yaml
added the ENABLE_SOCIAL_AUTH flag in template.yml
*
regarding https://issues.redhat.com/browse/CSSRE-2073
> added enable social auth to template.yml

- .github/CODEOWNERS
* Removing @deepak1725 from Codeowners
> removing deepak1725 as codeowner

- openshift/template.yaml
* Fix DVO checks which are failing.
The following DVO checks are failing for Glitchtip;
* minimum_three_replicas for glitchtip-beat and glitchtip worker
* default_service_account
https://issues.redhat.com/browse/CSSRE-2111
> Added fixes for DVO check failures

- cypress/e2e/login.cy.ts
- cypress/e2e/manage-emails.cy.ts
- cypress/e2e/reset-password.cy.ts
- openshift/template.yaml
- src/app/login/login.component.html
- src/app/login/login.component.spec.ts
- src/app/login/login.component.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
from frontend
* added the frontend changes for removal of login form options using environment variables
(from the ticket)
As a service owner, I want to be able to ensure that only the supported login form options are presented to a user so that;
1. I can minimize the possible security-related threats (attack vectors) related to those unsupported login form options.
2. Provide a simpler and correct customer experience.
https://issues.redhat.com/browse/CSSRE-2073
> CSSRE-2073: Removal of login form options

- cypress/e2e/login.cy.ts
- cypress/e2e/manage-emails.cy.ts
- cypress/e2e/reset-password.cy.ts
- src/app/login/login.component.html
- src/app/login/login.component.spec.ts
- src/app/login/login.component.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
Hi @Nanyte25 added overridden login changes from upstream
> added overridden changes from upstream

- openshift/template.yaml
Reverts rh-cssre/glitchtip-frontend#114
> Revert "updated the probes in template.yml"

- openshift/template.yaml
Updated the glitchtip worker readiness and liveness probes
regarding https://issues.redhat.com/browse/CSSRE-1899
1. https://issues.redhat.com/browse/CSSRE-1899
2. https://issues.redhat.com/browse/CSSRE-2058
> updated the worker liveness and readiness probes

- openshift/template.yaml
this is regarding https://issues.redhat.com/browse/CSSRE-2210
> added a comment to re-trigger the build

- sre/Dockerfile.sre
added quay gt-backend image for Dockerfile.sre
> modified Dockerfile gt-backend

- openshift/template.yaml
increased the timeoutSeconds on readiness and liveness probes for celery workers
> increased timeout for celery worker probes

- openshift/template.yaml
Added beat probes for glitchtip beat
> added beat probes

- openshift/template.yaml
* Fix the memory issue with bat deployment config https://issues.redhat.com/browse/CSSRE-1888
> fixing memory in beat deployment.

- openshift/template.yaml
*Fix request limits for beat deployment to get liveness and readiness probes to work
https://issues.redhat.com/browse/CSSRE-1888
> increasing the request limits for beat pod.

- openshift/template.yaml
Fixing Glitchtip liveness probes https://issues.redhat.com/browse/CSSRE-2058
> updateing liveness probe for glitchtip beat deployment.

- openshift/template.yaml
* Fixing replica and liveness probes https://issues.redhat.com/browse/CSSRE-2058
> update replica's to 2 fixing liveness probe.

- openshift/template.yaml
* Fixing Memory and Request Limits for bet pod https://issues.redhat.com/browse/CSSRE-2058
> fixing memory request and limits for beat deployment.

- openshift/template.yaml
gt-frontend trigger for checking out glitchtip-web pods with initialDelaySeconds increase
> checking web with increased initialDelaySeconds

- openshift/template.yaml
- sre/Dockerfile.sre
modified the upstream image and reverted the readinessprobes for gt-web
> modified upstream image

- openshift/template.yaml
* $TITLE
SMTP settings are stored in a kubernetes secret.
[APPSRE-6552](https://issues.redhat.com/browse/APPSRE-6552)
Must be merged AFTER https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/51657
> get smtp settings from k8s secret

- openshift/grafana/grafana-dashboard-glitchtip.configmap.yaml
updated the grafana configmap to read from datasource rather than predefined source, which will help us to view dashboards in both staging and production
> added datasources for grafana dashboard
